version: '3.8'

services:
  glpi:
    image: diouxx/glpi
    container_name: glpi-app
    hostname: glpi
    restart: unless-stopped
    networks:
      cosmos:
        ipv4_address: 192.168.95.63
    ports:
      - "82:80"
    volumes:
      - glpi_files:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
    depends_on:
      - glpi_db

  glpi_db:
    image: mariadb:10.11
    container_name: glpi-db
    hostname: glpi-db
    restart: unless-stopped
    networks:
      cosmos:
        ipv4_address: 192.168.95.64
    volumes:
      - glpi_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-root-pw # Changez ce mot de passe !
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=my-secret-glpi-pw # Changez ce mot de passe !
      - TZ=Europe/Paris
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  glpi_files:
  glpi_db:

networks:
  cosmos:
    external: true
    name: cosmos
